// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOPCloI9wxOpR5z6otnT_oM7jPaZlVvkQ',
    appId: '1:370195356495:web:2d6535bc47929789e3033a',
    messagingSenderId: '370195356495',
    projectId: 'vito-app-463903',
    authDomain: 'vito-app-463903.firebaseapp.com',
    storageBucket: 'vito-app-463903.firebasestorage.app',
    measurementId: 'G-TSMKNM31X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ7Na9osF9y2YKse9Nirb6nImjQMIAseY',
    appId: '1:370195356495:android:b84b75b1515132cde3033a',
    messagingSenderId: '370195356495',
    projectId: 'vito-app-463903',
    storageBucket: 'vito-app-463903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwP7qs6r5HPSKpxHio0N-ybuFVZbwIJlU',
    appId: '1:370195356495:ios:5330d12aaf8325c6e3033a',
    messagingSenderId: '370195356495',
    projectId: 'vito-app-463903',
    storageBucket: 'vito-app-463903.firebasestorage.app',
    iosClientId: '370195356495-s7vve60qnj4qj2kdr2e3m34o6vtfs7p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwP7qs6r5HPSKpxHio0N-ybuFVZbwIJlU',
    appId: '1:370195356495:ios:5330d12aaf8325c6e3033a',
    messagingSenderId: '370195356495',
    projectId: 'vito-app-463903',
    storageBucket: 'vito-app-463903.firebasestorage.app',
    iosClientId: '370195356495-s7vve60qnj4qj2kdr2e3m34o6vtfs7p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOPCloI9wxOpR5z6otnT_oM7jPaZlVvkQ',
    appId: '1:370195356495:web:1775b0202212ca8de3033a',
    messagingSenderId: '370195356495',
    projectId: 'vito-app-463903',
    authDomain: 'vito-app-463903.firebaseapp.com',
    storageBucket: 'vito-app-463903.firebasestorage.app',
    measurementId: 'G-E7D3K8PCTS',
  );
}
